export const accordionGroup = {
	allowMultiple: (
		baseURL: string,
	) => `<!-- wp:launchpad-blocks/accordion-group {"isMultiple":true,"accordionGroupId":"808d73aa-c033-4121-8566-83b270df7de8"} -->
<div id="808d73aa-c033-4121-8566-83b270df7de8" data-accordion-group="" data-is-multiple="true" class="wp-block-launchpad-blocks-accordion-group"><!-- wp:launchpad-blocks/accordion {"isInitiallyOpen":true,"accordionId":"371cd9f8-a34f-400c-9872-c1bc91c5dfd1","headerContent":"Accordion that is open by default"} -->
<div data-accordion="" data-is-initially-open="true" id="371cd9f8-a34f-400c-9872-c1bc91c5dfd1" class="wp-block-launchpad-blocks-accordion"><h2><button aria-expanded="true" aria-controls="371cd9f8-a34f-400c-9872-c1bc91c5dfd1-panel" data-state="open" id="371cd9f8-a34f-400c-9872-c1bc91c5dfd1-trigger" class="accordion-header-button"><span class="accordion-header-button-text">Accordion that is open by default</span><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" class="accordion-header-button-icon"><use href="${baseURL}/wp-content/plugins/launchpad-blocks/build/icons/sprite.svg#accordion-arrow"></use></svg></button></h2><div role="region" data-state="open" aria-labelledby="371cd9f8-a34f-400c-9872-c1bc91c5dfd1-trigger" id="371cd9f8-a34f-400c-9872-c1bc91c5dfd1-panel" class="accordion-panel"><div class="accordion-panel-inner-wrapper"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:launchpad-blocks/accordion -->

<!-- wp:launchpad-blocks/accordion {"isInitiallyOpen":true,"accordionId":"b9bc28e8-8511-4a15-bea7-5fe96855ce3a","headerContent":"Accordion that is open by default if multiple accordions allowed"} -->
<div data-accordion="" data-is-initially-open="true" id="b9bc28e8-8511-4a15-bea7-5fe96855ce3a" class="wp-block-launchpad-blocks-accordion"><h2><button aria-expanded="true" aria-controls="b9bc28e8-8511-4a15-bea7-5fe96855ce3a-panel" data-state="open" id="b9bc28e8-8511-4a15-bea7-5fe96855ce3a-trigger" class="accordion-header-button"><span class="accordion-header-button-text">Accordion that is open by default if multiple accordions allowed</span><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" class="accordion-header-button-icon"><use href="${baseURL}/wp-content/plugins/launchpad-blocks/build/icons/sprite.svg#accordion-arrow"></use></svg></button></h2><div role="region" data-state="open" aria-labelledby="b9bc28e8-8511-4a15-bea7-5fe96855ce3a-trigger" id="b9bc28e8-8511-4a15-bea7-5fe96855ce3a-panel" class="accordion-panel"><div class="accordion-panel-inner-wrapper"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:launchpad-blocks/accordion -->

<!-- wp:launchpad-blocks/accordion {"accordionId":"d749df67-c0a1-40d8-b36c-2ad03464118d","headerContent":"Accordion that is closed by default"} -->
<div data-accordion="" data-is-initially-open="false" id="d749df67-c0a1-40d8-b36c-2ad03464118d" class="wp-block-launchpad-blocks-accordion"><h2><button aria-expanded="true" aria-controls="d749df67-c0a1-40d8-b36c-2ad03464118d-panel" data-state="open" id="d749df67-c0a1-40d8-b36c-2ad03464118d-trigger" class="accordion-header-button"><span class="accordion-header-button-text">Accordion that is closed by default</span><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" class="accordion-header-button-icon"><use href="${baseURL}/wp-content/plugins/launchpad-blocks/build/icons/sprite.svg#accordion-arrow"></use></svg></button></h2><div role="region" data-state="open" aria-labelledby="d749df67-c0a1-40d8-b36c-2ad03464118d-trigger" id="d749df67-c0a1-40d8-b36c-2ad03464118d-panel" class="accordion-panel"><div class="accordion-panel-inner-wrapper"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:launchpad-blocks/accordion --></div>
<!-- /wp:launchpad-blocks/accordion-group -->`,
	doesNotAllowMultiple: (
		baseURL: string,
	) => `<!-- wp:launchpad-blocks/accordion-group {"accordionGroupId":"b72e6609-baac-46a4-884c-70e6750f3aa7"} -->
<div id="b72e6609-baac-46a4-884c-70e6750f3aa7" data-accordion-group="" data-is-multiple="false" class="wp-block-launchpad-blocks-accordion-group"><!-- wp:launchpad-blocks/accordion {"isInitiallyOpen":true,"accordionId":"8ea79320-714f-4645-9c45-856720fb6ee3","headerContent":"Accordion that is open by default"} -->
<div data-accordion="" data-is-initially-open="true" id="8ea79320-714f-4645-9c45-856720fb6ee3" class="wp-block-launchpad-blocks-accordion"><h2><button aria-expanded="true" aria-controls="8ea79320-714f-4645-9c45-856720fb6ee3-panel" data-state="open" id="8ea79320-714f-4645-9c45-856720fb6ee3-trigger" class="accordion-header-button"><span class="accordion-header-button-text">Accordion that is open by default</span><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" class="accordion-header-button-icon"><use href="${baseURL}/wp-content/plugins/launchpad-blocks/build/icons/sprite.svg#accordion-arrow"></use></svg></button></h2><div role="region" data-state="open" aria-labelledby="8ea79320-714f-4645-9c45-856720fb6ee3-trigger" id="8ea79320-714f-4645-9c45-856720fb6ee3-panel" class="accordion-panel"><div class="accordion-panel-inner-wrapper"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:launchpad-blocks/accordion -->

<!-- wp:launchpad-blocks/accordion {"isInitiallyOpen":true,"accordionId":"15311922-f686-44a1-b104-66d0e83698ff","headerContent":"Accordion that is open by default if multiple accordions allowed"} -->
<div data-accordion="" data-is-initially-open="true" id="15311922-f686-44a1-b104-66d0e83698ff" class="wp-block-launchpad-blocks-accordion"><h2><button aria-expanded="true" aria-controls="15311922-f686-44a1-b104-66d0e83698ff-panel" data-state="open" id="15311922-f686-44a1-b104-66d0e83698ff-trigger" class="accordion-header-button"><span class="accordion-header-button-text">Accordion that is open by default if multiple accordions allowed</span><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" class="accordion-header-button-icon"><use href="${baseURL}/wp-content/plugins/launchpad-blocks/build/icons/sprite.svg#accordion-arrow"></use></svg></button></h2><div role="region" data-state="open" aria-labelledby="15311922-f686-44a1-b104-66d0e83698ff-trigger" id="15311922-f686-44a1-b104-66d0e83698ff-panel" class="accordion-panel"><div class="accordion-panel-inner-wrapper"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:launchpad-blocks/accordion -->

<!-- wp:launchpad-blocks/accordion {"accordionId":"03dbfc94-c80f-4c6c-a25d-914b5c2d75ca","headerContent":"Accordion that is closed by default"} -->
<div data-accordion="" data-is-initially-open="false" id="03dbfc94-c80f-4c6c-a25d-914b5c2d75ca" class="wp-block-launchpad-blocks-accordion"><h2><button aria-expanded="true" aria-controls="03dbfc94-c80f-4c6c-a25d-914b5c2d75ca-panel" data-state="open" id="03dbfc94-c80f-4c6c-a25d-914b5c2d75ca-trigger" class="accordion-header-button"><span class="accordion-header-button-text">Accordion that is closed by default</span><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" class="accordion-header-button-icon"><use href="${baseURL}/wp-content/plugins/launchpad-blocks/build/icons/sprite.svg#accordion-arrow"></use></svg></button></h2><div role="region" data-state="open" aria-labelledby="03dbfc94-c80f-4c6c-a25d-914b5c2d75ca-trigger" id="03dbfc94-c80f-4c6c-a25d-914b5c2d75ca-panel" class="accordion-panel"><div class="accordion-panel-inner-wrapper"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:launchpad-blocks/accordion --></div>
<!-- /wp:launchpad-blocks/accordion-group -->`,
};
